- hosts: all
  tasks:
    - group_by: key={{ ansible_os_family }}

- hosts: RedHat
  gather_facts: False
  tasks:
    - name: install fpm requirements
      yum: name={{ item }} state=latest
      with_items:
        - ruby-devel
        - gcc
        - make
        - rpm-build
    # NOTE: Fix FFI #368 on Centos 7:
    # https://github.com/ffi/ffi/issues/368
    - name: install ffi
      gem: name=ffi state=latest build_flags='--platform=ruby' user_install=no
    - name: install fpm
      gem: name=fpm state=latest user_install=no

- hosts: Debian
  gather_facts: False
  tasks:
    - name: install fpm requirements
      apt: name={{ item }} state=latest
      with_items:
        - ruby-dev
        - gcc
        - make
    - name: install fpm
      gem: name=fpm state=latest user_install=no

