---
- name: Debian
  hosts: all
  tasks:
    - name: add apt over https
      apt:
        name: apt-transport-https
        state: latest
    - name: add snap key
      apt_key:
        url: https://packagecloud.io/intelsdi-x/snap/gpgkey
        state: present
    - name: add snap repo
      apt_repository:
        repo: "deb https://packagecloud.io/intelsdi-x/snap/ubuntu/ {{ ansible_distribution_release }} main"
        state: present
    - name: install snap
      apt:
        deb: "/artifacts/pkg/os/ubuntu/{{ ansible_distribution_version }}/snap-telemetry_0.15.0-1{{ ansible_distribution_release }}_amd64.deb"
        state: present
    - name: enable snap service
      service:
        name: snap-telemetry
        state: started
        enabled: yes
