---
- name: Debian
  hosts: all
  tasks:
    - name: install fpm requirements
      apt: name={{ item }} state=latest
      with_items:
        - ruby-dev
        - gcc
        - make
    - name: install fpm
      gem: name=fpm state=latest user_install=no
