---
- name: RedHat
  hosts: all
  tasks:
    - name: include snap repository
      yum_repository:
        name: snap
        description: Packagecloud.io snap repository
        baseurl: https://packagecloud.io/intelsdi-x/snap/el/$releasever/$basearch
        enabled: yes
        repo_gpgcheck: yes
        gpgcheck: no
        gpgkey: https://packagecloud.io/intelsdi-x/snap/gpgkey
        sslverify: yes
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    - name: install snap
      yum:
        name: "/vagrant/artifacts/pkg/os/redhat/{{ ansible_distribution_version.split('.')[0] }}/snap-telemetry-{{ snap_version }}-1.el{{ ansible_distribution_version.split('.')[0] }}.x86_64.rpm"
        state: present
    - name: enable snap service
      service:
        name: snap-telemetry
        state: started
        enabled: yes
